// AlphaFundamental — Ticker Universe (Updated 2026-05-12)
// Format: [ticker, name, sector, industry, moatRating, moatSources, risk1, risk2]
const RAW = [
  ["MRAM","Everspin Technologies","Technology","MRAM Memory","None",[],"Niche market size","Competition from larger memory players"],
  ["NVTS","Navitas Semiconductor","Technology","Power Semiconductors","Narrow",["Intangible Assets"],"Pre-profitability risk","GaN adoption pace"],
  ["MTZ","MasTec","Industrials","Infrastructure Construction","Narrow",["Cost Advantages"],"Project execution risk","Energy transition pace"],
  ["ICHR","Ichor Holdings","Technology","Semiconductor Equipment","Narrow",["Switching Costs"],"Semiconductor capex cyclicality","Customer concentration"],
  ["AEIS","Advanced Energy Industries","Technology","Power Solutions","Narrow",["Switching Costs"],"Semiconductor cycle exposure","End-market diversification risk"],
  ["BELFB","Bel Fuse","Industrials","Electronic Components","None",[],"Customer concentration","Commodity pricing pressure"],
  ["EOSE","Eos Energy Enterprises","Energy","Energy Storage","None",[],"Pre-profitability risk","Battery technology competition"],
  ["SITM","SiTime Corporation","Technology","MEMS Timing","Narrow",["Intangible Assets"],"Niche market risk","Quartz timing competition"],
  ["DGXX","Digi International","Technology","IoT Solutions","Narrow",["Switching Costs"],"IoT adoption pace","Competition from larger players"],
  ["PLAB","Photronics","Technology","Photomasks","Narrow",["Efficient Scale"],"Semiconductor cycle dependency","Technology node transitions"],
  ["AMKR","Amkor Technology","Technology","Semiconductor Packaging","Narrow",["Cost Advantages"],"Customer concentration","Geopolitical risk in Asia"],
  ["MXL","MaxLinear","Technology","Semiconductors","Narrow",["Intangible Assets"],"Broadband market cyclicality","Integration risk"],
  ["GRRR","Gorilla Technology","Technology","AI & Security","None",[],"Small-cap execution risk","Competition from larger AI players"],
  ["IRM","Iron Mountain","Real Estate","Data Storage REITs","Wide",["Switching Costs","Efficient Scale"],"Digital disruption of physical storage","Interest rate sensitivity"],
  ["CLS","Celestica","Technology","EMS Manufacturing","Narrow",["Switching Costs"],"Customer concentration","Supply chain disruption"],
  ["TLN","Talen Energy","Utilities","Power Generation","Narrow",["Cost Advantages"],"Power price volatility","Regulatory risk"],
  ["NET","Cloudflare","Technology","CDN & Security","Narrow",["Network Effects"],"Path to profitability timeline","Enterprise sales execution"],
  ["ACLS","Axcelis Technologies","Technology","Ion Implant Equipment","Narrow",["Switching Costs"],"Semiconductor capex cycle","Technology transition risk"],
  ["VICR","Vicor Corporation","Technology","Power Modules","Narrow",["Intangible Assets"],"Niche market adoption","Competition from TI and Analog Devices"],
  ["RMBS","Rambus","Technology","Memory Interface IP","Narrow",["Intangible Assets"],"Patent portfolio risk","Memory market cyclicality"],
  ["MPWR","Monolithic Power Systems","Technology","Power Management ICs","Wide",["Intangible Assets","Switching Costs"],"Automotive cycle risk","Competition from TI and ADI"],
  ["CGNX","Cognex Corporation","Technology","Machine Vision","Wide",["Intangible Assets","Switching Costs"],"Factory automation cyclicality","Competition from Keyence"],
  ["OUST","Ouster","Technology","Lidar Sensors","None",[],"Lidar market uncertainty","Cash burn rate"],
  ["AMPX","Amprius Technologies","Technology","Battery Technology","None",[],"Pre-revenue scaling risk","Battery technology competition"],
  ["AAOI","Applied Optoelectronics","Technology","Optical Components","None",[],"Customer concentration","Pricing pressure"],
  ["LEU","Centrus Energy","Energy","Uranium Enrichment","Narrow",["Efficient Scale"],"Nuclear regulatory risk","Contract concentration"],
  ["ARM","ARM Holdings","Technology","Semiconductor IP","Wide",["Network Effects","Intangible Assets"],"RISC-V open-source competition","Royalty rate pressure"],
  ["CORZ","Core Scientific","Technology","Bitcoin Mining","None",[],"Bitcoin price volatility","Energy cost volatility"],
  ["ALAB","Astera Labs","Technology","Connectivity Semiconductors","Narrow",["Intangible Assets"],"Customer concentration","Data center spending volatility"],
  ["STRL","Sterling Infrastructure","Industrials","Infrastructure Construction","Narrow",["Cost Advantages"],"Construction cycle sensitivity","Labor cost inflation"],
  ["NNE","Nano Nuclear Energy","Energy","Nuclear SMR","None",[],"Pre-revenue technology risk","Regulatory approval uncertainty"],
  ["FN","Fabrinet","Technology","Optical Manufacturing","Narrow",["Switching Costs"],"Customer concentration","Telecom capex cyclicality"],
  ["USAR","USA Rare Earth","Materials","Rare Earth Mining","None",[],"Commodity price volatility","Pre-revenue execution risk"],
  ["ASTS","AST SpaceMobile","Technology","Satellite Communications","None",[],"Technology execution risk","Capital intensity"],
  ["TER","Teradyne","Technology","Semiconductor Test Equipment","Wide",["Switching Costs","Intangible Assets"],"Semiconductor test cycle","Robotics segment uncertainty"],
  ["COHR","Coherent Corp","Technology","Photonics & Lasers","Narrow",["Intangible Assets"],"Integration risk from acquisitions","End-market cyclicality"],
  ["RKLB","Rocket Lab USA","Industrials","Space Launch","Narrow",["Intangible Assets"],"Launch competition from SpaceX","Capital intensity"],
  ["HUT","Hut 8 Corp","Technology","Bitcoin Mining","None",[],"Bitcoin price volatility","Energy cost volatility"],
  ["MRVL","Marvell Technology","Technology","Semiconductors","Narrow",["Intangible Assets"],"Custom silicon competition","Data center spending volatility"],
  ["IREN","Iris Energy","Technology","Bitcoin Mining","None",[],"Bitcoin price volatility","Energy cost volatility"],
  ["ONTO","Onto Innovation","Technology","Semiconductor Inspection","Narrow",["Switching Costs"],"Semiconductor capex cycle","Customer concentration"],
  ["AMSC","American Superconductor","Industrials","Power Electronics","Narrow",["Intangible Assets"],"Grid modernization pace","Navy contract dependency"],
  ["WULF","TeraWulf","Technology","Bitcoin Mining","None",[],"Bitcoin price volatility","Regulatory risk"],
  ["CRWV","CrowdStrike Ventures","Technology","Cybersecurity","Narrow",["Switching Costs"],"Outage reputational risk","Microsoft security competition"],
  ["CIEN","Ciena Corporation","Technology","Optical Networking","Narrow",["Intangible Assets"],"Telecom capex cyclicality","5G deployment pace"],
  ["DOCN","DigitalOcean","Technology","Cloud Infrastructure","Narrow",["Switching Costs"],"SMB customer churn","Hyperscaler competition"],
  ["GEV","GE Vernova","Industrials","Power Equipment","Narrow",["Switching Costs"],"Wind turbine losses","Energy transition execution"],
  ["NOK","Nokia","Technology","Telecom Equipment","Narrow",["Intangible Assets"],"5G capex cycle","Ericsson competition"],
  ["APLD","Applied Digital","Technology","Data Center & AI Cloud","None",[],"Capital intensity","Customer concentration"],
  ["PLPC","Preformed Line Products","Industrials","Utility Hardware","Narrow",["Switching Costs"],"Utility capex cyclicality","Raw material costs"],
  ["CIFR","Cipher Mining","Technology","Bitcoin Mining","None",[],"Bitcoin price volatility","Energy cost risk"],
  ["NBIS","Nebius Group","Technology","AI Cloud Infrastructure","None",[],"AI spending sustainability","Competition from hyperscalers"],
  ["ETN","Eaton Corp","Industrials","Electrical Equipment","Narrow",["Cost Advantages","Switching Costs"],"Industrial cycle downturn","Raw material cost pressure"],
  ["VRT","Vertiv Holdings","Industrials","Data Center Infra","Narrow",["Switching Costs"],"Data center build-out slowdown","Supply chain constraints"],
  ["CRDO","Credo Technology","Technology","Connectivity Semiconductors","Narrow",["Intangible Assets"],"Customer concentration","Data center spending cycle"],
  ["MP","MP Materials","Materials","Rare Earth Mining","Narrow",["Cost Advantages"],"Rare earth price volatility","China competition"],
  ["EMR","Emerson Electric","Industrials","Automation","Wide",["Switching Costs","Cost Advantages"],"Industrial cycle sensitivity","Portfolio transformation risk"],
  ["POWL","Powell Industries","Industrials","Electrical Equipment","Narrow",["Switching Costs"],"Energy capex cyclicality","Project backlog risk"],
  ["PWR","Quanta Services","Industrials","Utility Construction","Narrow",["Cost Advantages"],"Labor shortage","Project execution risk"],
  ["TMQ","Trilogy Metals","Materials","Mining","None",[],"Commodity price volatility","Permitting risk"],
  ["AMAT","Applied Materials","Technology","Semiconductor Equipment","Wide",["Switching Costs","Intangible Assets"],"Wafer fab equipment cycle downturn","China revenue restrictions"],
  ["CCJ","Cameco","Energy","Uranium","Narrow",["Cost Advantages"],"Uranium price volatility","Nuclear sentiment shifts"],
  ["NTDOY","Nintendo","Consumer Discretionary","Gaming","Wide",["Intangible Assets","Network Effects"],"Console cycle risk","Mobile gaming competition"],
  ["VIAV","VIAV Solutions","Technology","Network Test","Narrow",["Switching Costs"],"Telecom capex cyclicality","Fiber deployment pace"],
  ["ANET","Arista Networks","Technology","Data Center Networking","Wide",["Switching Costs","Intangible Assets"],"Data center spending cyclicality","Cisco competition"],
  ["VLN","Valens Semiconductor","Technology","Connectivity Chips","None",[],"Automotive adoption pace","Customer concentration"],
  ["CLSK","CleanSpark","Technology","Bitcoin Mining","None",[],"Bitcoin price volatility","Energy cost risk"],
  ["LRCX","Lam Research","Technology","Semiconductor Equipment","Wide",["Switching Costs"],"Semiconductor capex cycle","China export controls"],
  ["DELL","Dell Technologies","Technology","IT Infrastructure","Narrow",["Cost Advantages"],"PC market cyclicality","Server margin pressure"],
  ["CEG","Constellation Energy","Utilities","Nuclear Power","Wide",["Cost Advantages","Efficient Scale"],"Nuclear regulatory risk","Power price volatility"],
  ["SPXC","SPX Technologies","Industrials","HVAC & Detection","Narrow",["Switching Costs"],"Construction cycle","Acquisition integration risk"],
  ["O","Realty Income","Real Estate","Net Lease REIT","Wide",["Cost Advantages","Efficient Scale"],"Interest rate sensitivity","Retail tenant risk"],
  ["FIX","Comfort Systems USA","Industrials","Mechanical Contracting","Narrow",["Cost Advantages"],"Construction cycle","Labor cost inflation"],
  ["CAT","Caterpillar","Industrials","Construction Equipment","Wide",["Intangible Assets","Cost Advantages"],"Construction cycle downturn","China economic slowdown"],
  ["TSEM","Tower Semiconductor","Technology","Semiconductor Foundry","Narrow",["Switching Costs"],"Analog chip demand cyclicality","Geopolitical risk"],
  ["AMD","AMD","Technology","Semiconductors","Narrow",["Intangible Assets"],"Intense competition from NVIDIA in AI","PC market cyclicality"],
  ["AVGO","Broadcom","Technology","Semiconductors","Wide",["Switching Costs","Cost Advantages"],"Customer concentration risk","VMware integration execution"],
  ["MU","Micron","Technology","Memory","Narrow",["Cost Advantages"],"Memory price cyclicality","Oversupply risk"],
  ["FORM","FormFactor","Technology","Semiconductor Probes","Narrow",["Switching Costs"],"Semiconductor test cycle","Customer concentration"],
  ["KLAC","KLA Corp","Technology","Semiconductor Equipment","Wide",["Switching Costs","Intangible Assets"],"Capex cycle downturn","Customer concentration"],
  ["VST","Vistra Energy","Utilities","Power Generation","Narrow",["Cost Advantages"],"Natural gas price volatility","Renewable energy competition"],
  ["CW","Curtiss-Wright","Industrials","Defense & Industrial","Narrow",["Switching Costs"],"Defense budget uncertainty","Nuclear regulation risk"],
  ["BWXT","BWX Technologies","Industrials","Nuclear Components","Wide",["Intangible Assets","Efficient Scale"],"Government contract dependency","Nuclear regulatory risk"],
  ["DLR","Digital Realty","Real Estate","Data Center REITs","Narrow",["Switching Costs"],"Interest rate pressure","Hyperscaler competition"],
  ["FERG","Ferguson Enterprises","Industrials","Plumbing Distribution","Wide",["Cost Advantages","Switching Costs"],"Housing cycle sensitivity","Raw material inflation"],
  ["HPE","Hewlett Packard Enterprise","Technology","IT Infrastructure","Narrow",["Switching Costs"],"Server margin compression","Cloud migration cannibalization"],
  ["NEE","NextEra Energy","Utilities","Renewables","Wide",["Cost Advantages","Efficient Scale"],"Interest rate sensitivity","Policy changes on renewables"],
  ["EME","EMCOR Group","Industrials","Electrical Contracting","Narrow",["Cost Advantages"],"Construction cycle","Labor shortage"],
  ["EQT","EQT Corporation","Energy","Natural Gas","Narrow",["Cost Advantages"],"Natural gas price volatility","Regulatory risk on drilling"],
  ["EQIX","Equinix","Real Estate","Data Center REITs","Wide",["Network Effects","Switching Costs"],"Rising interest rates","Hyperscaler self-build risk"],
  ["DE","Deere & Co","Industrials","Farm Equipment","Wide",["Intangible Assets","Switching Costs"],"Farm income decline","Precision ag adoption pace"],
  ["HUBB","Hubbell","Industrials","Electrical Products","Narrow",["Switching Costs"],"Utility capex cyclicality","Raw material costs"],
  ["ASML","ASML","Technology","Semiconductor Equipment","Wide",["Intangible Assets","Efficient Scale"],"Semiconductor capex cyclicality","Export control restrictions"],
  ["PH","Parker Hannifin","Industrials","Motion & Control","Wide",["Switching Costs","Cost Advantages"],"Industrial cycle downturn","Aerospace aftermarket risk"],
  ["APD","Air Products","Materials","Industrial Gases","Wide",["Cost Advantages","Efficient Scale"],"Capital project execution","Energy transition pace"],
  ["MOD","Modine Manufacturing","Industrials","Thermal Management","Narrow",["Switching Costs"],"EV adoption pace uncertainty","Customer concentration"],
  ["LIN","Linde","Materials","Industrial Gases","Wide",["Cost Advantages","Efficient Scale"],"Industrial production slowdown","Energy cost volatility"],
  ["NU","Nu Holdings","Financials","Digital Banking","Narrow",["Network Effects"],"Latin American economic risk","Regulatory changes"],
  ["OSS","One Stop Systems","Technology","Edge Computing","None",[],"Small-cap execution risk","Defense contract dependency"],
  ["ATI","ATI Inc","Materials","Specialty Metals","Narrow",["Switching Costs"],"Aerospace cycle risk","Raw material cost volatility"],
  ["TXN","Texas Instruments","Technology","Analog Semiconductors","Wide",["Cost Advantages","Switching Costs"],"Analog cycle downturn","Capex ramp risk from new fabs"],
  ["AMZN","Amazon","Technology","E-Commerce & Cloud","Wide",["Network Effects","Cost Advantages"],"AWS competition from Azure/GCP","Retail margin compression"],
  ["APH","Amphenol","Industrials","Connectors","Wide",["Switching Costs","Cost Advantages"],"Industrial cycle sensitivity","Automotive market weakness"],
  ["RMD","ResMed","Healthcare","Medical Devices","Wide",["Switching Costs","Intangible Assets"],"GLP-1 impact on sleep apnea","Regulatory approval risk"],
  ["ODFL","Old Dominion Freight","Industrials","LTL Trucking","Wide",["Cost Advantages","Efficient Scale"],"Freight recession","Labor cost inflation"],
  ["TSM","TSMC","Technology","Semiconductor Mfg","Wide",["Cost Advantages","Efficient Scale"],"Geopolitical Taiwan risk","Capex intensity pressure"],
  ["IESC","IES Holdings","Industrials","Electrical Contracting","Narrow",["Cost Advantages"],"Construction cycle sensitivity","Labor market tightness"],
  ["IDXX","IDEXX Laboratories","Healthcare","Veterinary Diagnostics","Wide",["Switching Costs","Efficient Scale"],"Veterinary visit volume decline","International expansion risk"],
  ["UEC","Uranium Energy Corp","Energy","Uranium Mining","None",[],"Uranium price volatility","Permitting and regulatory risk"],
  ["GE","GE Aerospace","Industrials","Aerospace","Wide",["Switching Costs","Intangible Assets"],"Supply chain bottlenecks","Engine defect liabilities"],
  ["CARR","Carrier Global","Industrials","HVAC","Wide",["Intangible Assets","Switching Costs"],"Construction cycle sensitivity","Refrigerant regulation"],
  ["IRDM","Iridium Communications","Technology","Satellite Communications","Wide",["Efficient Scale"],"Technology disruption from LEO competitors","Government contract dependency"],
  ["PDFS","PDF Solutions","Technology","Semiconductor Analytics","Narrow",["Switching Costs"],"Semiconductor cycle dependency","Customer concentration"],
  ["UUUU","Energy Fuels","Energy","Uranium & Rare Earth","None",[],"Uranium price volatility","Rare earth processing scale-up risk"],
  ["MTD","Mettler-Toledo","Healthcare","Lab Instruments","Wide",["Switching Costs","Intangible Assets"],"Pharma R&D spending cuts","China market uncertainty"],
  ["AEP","American Electric Power","Utilities","Electric Utilities","Wide",["Efficient Scale"],"Regulatory rate decisions","Capital-intensive grid modernization"],
  ["CME","CME Group","Financials","Exchanges","Wide",["Network Effects","Efficient Scale"],"Volume cyclicality","Regulatory changes"],
  ["ENS","EnerSys","Industrials","Battery Systems","Narrow",["Switching Costs"],"Raw material cost volatility","EV transition impact"],
  ["FCX","Freeport-McMoRan","Materials","Copper Mining","Narrow",["Cost Advantages"],"Copper price volatility","Geopolitical risk in Indonesia"],
  ["UMC","United Microelectronics","Technology","Semiconductor Foundry","Narrow",["Cost Advantages"],"Foundry price pressure","Technology node limitations"],
  ["GNRC","Generac Holdings","Industrials","Power Generation","Narrow",["Intangible Assets"],"Demand normalization post-storms","Clean energy transition"],
  ["AMT","American Tower","Real Estate","Cell Tower REITs","Wide",["Efficient Scale","Switching Costs"],"Interest rate sensitivity","Carrier consolidation risk"],
  ["KYCCF","Keyence Corp","Technology","Factory Automation","Wide",["Intangible Assets","Switching Costs"],"Japanese yen volatility","Automation cycle downturn"],
  ["AAPL","Apple","Technology","Consumer Electronics","Wide",["Switching Costs","Intangible Assets"],"iPhone cycle maturation","Regulatory antitrust pressure"],
  ["SSNLF","Samsung Electronics","Technology","Semiconductors & Electronics","Wide",["Cost Advantages","Intangible Assets"],"Memory price cyclicality","Smartphone market saturation"],
  ["GOOGL","Alphabet","Technology","Internet Services","Wide",["Network Effects","Intangible Assets"],"AI disruption of search","Antitrust remedies risk"],
  ["WCN","Waste Connections","Industrials","Waste Management","Wide",["Cost Advantages","Efficient Scale"],"Environmental regulation costs","Acquisition integration risk"],
  ["SNPS","Synopsys","Technology","EDA Software","Wide",["Switching Costs","Efficient Scale"],"Ansys integration risk","Semiconductor cycle sensitivity"],
  ["ORCL","Oracle","Technology","Enterprise Software","Wide",["Switching Costs"],"Cloud migration execution","Competition from hyperscalers"],
  ["ROL","Rollins","Consumer Discretionary","Pest Control","Wide",["Switching Costs","Cost Advantages"],"Labor cost inflation","Weather pattern disruption"],
  ["ISRG","Intuitive Surgical","Healthcare","Medical Devices","Wide",["Switching Costs","Intangible Assets"],"Emerging robotic surgery competitors","Hospital capital spending cuts"],
  ["AWK","American Water Works","Utilities","Water Utilities","Wide",["Efficient Scale","Cost Advantages"],"Regulatory rate decisions","Capital-intensive infrastructure"],
  ["WM","Waste Management","Industrials","Waste Management","Wide",["Cost Advantages","Efficient Scale"],"Environmental regulation costs","Recycling commodity price swings"],
  ["GLW","Corning","Technology","Specialty Glass","Wide",["Intangible Assets","Switching Costs"],"Display market cyclicality","Optical fiber demand volatility"],
  ["TMUS","T-Mobile US","Technology","Wireless Telecom","Narrow",["Cost Advantages"],"Wireless competition intensity","Spectrum cost escalation"],
  ["CDNS","Cadence Design","Technology","EDA Software","Wide",["Switching Costs","Efficient Scale"],"Semiconductor industry downturn","AI disruption of chip design"],
  ["CSCO","Cisco Systems","Technology","Networking Equipment","Wide",["Switching Costs","Cost Advantages"],"Enterprise spending slowdown","SD-WAN disruption"],
  ["META","Meta Platforms","Technology","Social Media","Wide",["Network Effects"],"Metaverse investment uncertainty","Regulatory privacy restrictions"],
  ["TDG","TransDigm","Industrials","Aerospace Components","Wide",["Switching Costs","Intangible Assets"],"DOD pricing scrutiny","Aftermarket volume cyclicality"],
  ["V","Visa","Financials","Credit Services","Wide",["Network Effects","Intangible Assets"],"Fintech disruption","Regulatory pressure on interchange fees"],
  ["MSCI","MSCI Inc","Financials","Financial Data","Wide",["Switching Costs","Intangible Assets"],"Index fund fee compression","ESG backlash"],
  ["NTAP","NetApp","Technology","Data Storage","Narrow",["Switching Costs"],"Cloud migration cannibalization","Competition from Pure Storage"],
  ["SPGI","S&P Global","Financials","Financial Data","Wide",["Intangible Assets","Switching Costs"],"Regulatory changes","Integration risk from mergers"],
  ["COST","Costco","Consumer Staples","Retail","Wide",["Cost Advantages","Switching Costs"],"Membership fee resistance","E-commerce competition"],
  ["MSFT","Microsoft","Technology","Software","Wide",["Switching Costs","Network Effects"],"AI monetization execution risk","Antitrust regulatory pressure"],
  ["BKNG","Booking Holdings","Consumer Discretionary","Online Travel","Wide",["Network Effects","Intangible Assets"],"Travel demand cyclicality","Regulatory pressure in EU"],
  ["BB","BlackBerry","Technology","Cybersecurity & IoT","None",[],"Turnaround execution risk","Legacy business decline"],
  ["MA","Mastercard","Financials","Credit Services","Wide",["Network Effects","Intangible Assets"],"Fintech disruption","Regulatory pressure on fees"],
  ["NVDA","NVIDIA","Technology","Semiconductors","Wide",["Intangible Assets","Switching Costs"],"AI spending pullback","Export restrictions to China"],
  ["MCO","Moody's","Financials","Credit Ratings","Wide",["Intangible Assets","Efficient Scale"],"Regulatory scrutiny","Credit cycle downturn"],
  ["P","Pandora","Consumer Discretionary","Jewelry","Narrow",["Intangible Assets"],"Consumer discretionary spending","Brand competition"],
  ["PLTR","Palantir","Technology","Data Analytics","Narrow",["Switching Costs"],"Government contract concentration","High valuation risk"],
  ["CSGP","CoStar Group","Technology","Real Estate Data","Wide",["Network Effects","Switching Costs"],"Residential expansion execution","Competition from Zillow"],
  ["ALB","Albemarle","Materials","Lithium","Narrow",["Cost Advantages"],"Lithium price volatility","EV adoption pace uncertainty"],
  ["TSLA","Tesla","Consumer Discretionary","Electric Vehicles","Narrow",["Intangible Assets"],"EV competition intensifying","Valuation premium risk"],
  ["AXTI","AXT Inc","Technology","Compound Semiconductors","None",[],"Niche market cyclicality","China operations risk"],
  ["QCOM","Qualcomm","Technology","Mobile Semiconductors","Wide",["Intangible Assets","Cost Advantages"],"Apple modem transition","Smartphone market saturation"],
  ["HWM","Howmet Aerospace","Industrials","Aerospace Components","Narrow",["Switching Costs"],"Aerospace cycle risk","Raw material costs"],
  ["MTSI","MACOM Technology","Technology","RF Semiconductors","Narrow",["Intangible Assets"],"Telecom capex cyclicality","Defense contract concentration"],
  ["FLNC","Fluence Energy","Energy","Energy Storage","None",[],"Battery storage competition","Project execution risk"],
  ["ENTG","Entegris","Technology","Semiconductor Materials","Wide",["Switching Costs","Intangible Assets"],"Semiconductor capex cyclicality","Customer concentration risk"],
  ["PL","Planet Labs","Industrials","Aerospace & Defense","Narrow",["Intangible Assets"],"Path to profitability timeline","Launch competition from SpaceX"],
  ["SYNA","Synaptics","Technology","IoT Semiconductors","Narrow",["Intangible Assets","Switching Costs"],"Semiconductor cycle dependency","Competition from larger players"]
];

export const TICKERS_DATA = {};
export const TICKER_LIST = [];

RAW.forEach(r => {
  const obj = {
    ticker: r[0], name: r[1], sector: r[2], industry: r[3],
    moatRating: r[4], moatSources: r[5], risks: [r[6], r[7]]
  };
  TICKERS_DATA[r[0]] = obj;
  TICKER_LIST.push(obj);
});

export const SECTOR_AVERAGES = {
  "Financials": { pe: 15, forwardPE: 13, pfcf: 13, evEbitda: 11, peg: 1.4, roic: 0.12, opMargin: 0.30, revGrowth: 0.06, netDebtEbitda: 2.5 },
  "Technology": { pe: 32, forwardPE: 28, pfcf: 28, evEbitda: 22, peg: 1.8, roic: 0.18, opMargin: 0.25, revGrowth: 0.12, netDebtEbitda: 0.8 },
  "Healthcare": { pe: 25, forwardPE: 22, pfcf: 22, evEbitda: 18, peg: 1.6, roic: 0.15, opMargin: 0.20, revGrowth: 0.08, netDebtEbitda: 1.5 },
  "Consumer Staples": { pe: 22, forwardPE: 20, pfcf: 20, evEbitda: 16, peg: 2.5, roic: 0.20, opMargin: 0.18, revGrowth: 0.04, netDebtEbitda: 2.0 },
  "Consumer Discretionary": { pe: 25, forwardPE: 22, pfcf: 22, evEbitda: 16, peg: 1.5, roic: 0.15, opMargin: 0.12, revGrowth: 0.07, netDebtEbitda: 1.8 },
  "Industrials": { pe: 22, forwardPE: 20, pfcf: 20, evEbitda: 15, peg: 1.7, roic: 0.14, opMargin: 0.15, revGrowth: 0.06, netDebtEbitda: 1.5 },
  "Energy": { pe: 12, forwardPE: 10, pfcf: 10, evEbitda: 8, peg: 1.0, roic: 0.12, opMargin: 0.15, revGrowth: 0.03, netDebtEbitda: 1.2 },
  "Utilities": { pe: 18, forwardPE: 16, pfcf: 15, evEbitda: 12, peg: 2.8, roic: 0.08, opMargin: 0.25, revGrowth: 0.04, netDebtEbitda: 4.0 },
  "Real Estate": { pe: 35, forwardPE: 30, pfcf: 25, evEbitda: 20, peg: 3.0, roic: 0.05, opMargin: 0.30, revGrowth: 0.05, netDebtEbitda: 5.0 },
  "Materials": { pe: 18, forwardPE: 16, pfcf: 16, evEbitda: 12, peg: 1.3, roic: 0.12, opMargin: 0.15, revGrowth: 0.05, netDebtEbitda: 1.5 }
};
